import { Request } from 'express';
import { ObjectId } from 'mongodb';

/**
 * Represents a resume document.
 * - `userId`: The username of the user who owns the resume.
 * - `fileName`: The original name of the uploaded file.
 * - `fileData`: The binary data of the resume file.
 * - `contentType`: The MIME type of the file (e.g., 'application/pdf').
 * - `fileSize`: The size of the file in bytes.
 * - `uploadDate`: The date when the resume was uploaded.
 * - `isActive`: Whether this is the user's active resume.
 */
export interface Resume {
  userId: string;
  fileName: string;
  fileData: Buffer;
  contentType: string;
  fileSize: number;
  uploadDate: Date;
  isActive: boolean;
}

/**
 * Represents a resume document in the database.
 * - `userId`: The username of the user who owns the resume.
 * - `fileName`: The original name of the uploaded file.
 * - `fileData`: The binary data of the resume file.
 * - `contentType`: The MIME type of the file.
 * - `fileSize`: The size of the file in bytes.
 * - `uploadDate`: The date when the resume was uploaded.
 * - `isActive`: Whether this is the user's active resume.
 * - `_id`: The unique identifier for the resume, generated by MongoDB.
 */
export interface DatabaseResume extends Resume {
  _id: ObjectId;
}

/**
 * Represents a "safe" resume object that excludes sensitive binary data.
 * Used when returning resume information without the actual file content.
 */
export type SafeDatabaseResume = Omit<DatabaseResume, 'fileData'>;

/**
 * Represents the response for resume-related operations.
 * - `SafeDatabaseResume`: A resume object without binary data if the operation is successful.
 * - `error`: An error message if the operation fails.
 */
export type ResumeResponse = SafeDatabaseResume | { error: string };

/**
 * Represents the response for multiple resume-related operations.
 * - `SafeDatabaseResume[]`: A list of resume objects without binary data if the operation is successful.
 * - `error`: An error message if the operation fails.
 */
export type ResumesResponse = SafeDatabaseResume[] | { error: string };

/**
 * Express request for uploading a resume.
 * - `userId`: The username of the user uploading the resume (body).
 * - `isActive`: Whether to set this resume as active (body).
 * - `resume`: The resume file (multipart form data).
 */
export interface UploadResumeRequest extends Request {
  body: {
    userId: string;
    isActive?: boolean;
  };
  file?: Express.Multer.File;
}

/**
 * Express request for resume operations by ID.
 * - `resumeId`: The resume ID provided as a route parameter.
 */
export interface ResumeByIdRequest extends Request {
  params: {
    resumeId: string;
  };
}

/**
 * Express request for user's resumes.
 * - `userId`: The username provided as a route parameter.
 */
export interface UserResumesRequest extends Request {
  params: {
    userId: string;
  };
}

/**
 * Express request for setting a user's active resume.
 * - `userId`: The username whose active resume is being set (body).
 * - `resumeId`: The ID of the resume to set as active (body).
 */
export interface SetActiveResumeRequest extends Request {
  body: {
    userId: string;
    resumeId: string;
  };
}

/**
 * Response type for resume download operations.
 * - `fileData`: The binary data of the resume file.
 * - `fileName`: The original name of the file.
 * - `contentType`: The MIME type of the file.
 * - `error`: An error message if the operation fails.
 */
export type ResumeDownloadResponse =
  | {
      fileData: Buffer;
      fileName: string;
      contentType: string;
    }
  | { error: string };